# Generated by Django 5.2.3 on 2025-08-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_payrolldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolldetails',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.employee'),
        ),
    ]
