# Generated by Django 5.2.3 on 2025-08-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_payrolldetails_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrolldetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='payrolldetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.employee', unique=True),
        ),
    ]
