# Generated by Django 5.2.3 on 2025-07-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_author_book_publisher_delete_person_delete_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
