# Generated by Django 5.2.3 on 2025-07-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_book_author_id_book_publisher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
