# Generated by Django 5.2.3 on 2025-07-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_username_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='username',
            name='count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='username',
            name='price',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='username',
            name='fisrtname',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
    ]
