# Generated by Django 5.2.3 on 2025-07-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_username_age_username_count_username_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('teachercode', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='username',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=10),
        ),
        migrations.AddField(
            model_name='username',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='username',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
