# Generated by Django 5.2.3 on 2025-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_teacher_username_cost_username_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(db_column='firstname', db_comment='', max_length=50),
        ),
    ]
